"""Persistence helpers shared by API routers."""

from persistence_domain.artifacts import (
    save_ats_report,
    save_cover_letter,
    save_job_offer,
    serialize_ats,
    serialize_cover_letter,
    serialize_job,
)
from persistence_domain.drafts import serialize_draft, upsert_workspace_draft
from persistence_domain.opportunities import (
    append_opportunity_transition,
    create_opportunity,
    create_or_attach_opportunity_application,
    link_opportunity_ats_report,
    link_opportunity_cover_letter,
    link_opportunity_resume,
    list_opportunity_transitions,
    mark_opportunity_ready_to_apply,
    repair_opportunity_integrity,
    serialize_opportunity,
    serialize_opportunity_transition,
)
from persistence_domain.resumes import (
    SUPPORTED_RESUME_LOCALES,
    activate_resume_locale_variant,
    compare_resume_revisions,
    create_resume,
    create_resume_locale_variant,
    create_resume_revision,
    delete_resume_locale_variant,
    get_current_cv,
    get_resume_revision,
    list_resume_revisions,
    localized_resume_record,
    resolve_resume_variant,
    save_current_cv,
    serialize_resume,
    serialize_resume_revision,
    update_resume,
)

__all__ = [
    "SUPPORTED_RESUME_LOCALES",
    "activate_resume_locale_variant",
    "append_opportunity_transition",
    "compare_resume_revisions",
    "create_opportunity",
    "create_or_attach_opportunity_application",
    "create_resume",
    "create_resume_locale_variant",
    "create_resume_revision",
    "delete_resume_locale_variant",
    "get_current_cv",
    "get_resume_revision",
    "link_opportunity_ats_report",
    "link_opportunity_cover_letter",
    "link_opportunity_resume",
    "list_opportunity_transitions",
    "list_resume_revisions",
    "localized_resume_record",
    "mark_opportunity_ready_to_apply",
    "repair_opportunity_integrity",
    "resolve_resume_variant",
    "save_ats_report",
    "save_cover_letter",
    "save_current_cv",
    "save_job_offer",
    "serialize_ats",
    "serialize_cover_letter",
    "serialize_draft",
    "serialize_job",
    "serialize_opportunity",
    "serialize_opportunity_transition",
    "serialize_resume",
    "serialize_resume_revision",
    "upsert_workspace_draft",
    "update_resume",
]
