"""Crew orchestration for the Mindris AI intelligence pipeline."""

from crewai import Crew, CrewOutput, Process

from .agents import MindrisAgents
from .tasks import MindrisTasks


class MindrisIntelligence:
    """High-level facade over a CrewAI crew for job-offer analysis.

    Usage::

        intelligence = MindrisIntelligence()
        result = intelligence.analyze_job(markdown_text, source_url)
    """

    def __init__(self) -> None:
        """Initialise agents and task factories."""
        self.agents = MindrisAgents()
        self.tasks = MindrisTasks()

    def analyze_job(self, job_markdown: str, url: str = "http://unknown") -> CrewOutput:
        """Analyse a job offer and return structured output.

        The URL and description are injected by the pipeline *after* the crew
        finishes, so the LLM only needs to produce the lightweight extraction
        fields (title, company, skills, …).

        Args:
            job_markdown: The job offer body in Markdown format.
            url: Source URL of the offer — stored on the result object by the
                caller, not generated by the LLM.

        Returns:
            A :class:`crewai.CrewOutput` whose ``.pydantic`` attribute holds a
            :class:`database.models.JobOffer` instance when parsing succeeds.
        """
        analyst = self.agents.job_analyst_agent()
        task = self.tasks.analysis_task(analyst, job_markdown, url)

        crew = Crew(
            agents=[analyst],
            tasks=[task],
            process=Process.sequential,
        )

        return crew.kickoff()
