"""Crew orchestration for the Mindris AI intelligence pipeline."""

import asyncio
import json
import logging

from crewai import Crew, CrewOutput, Process
from database.models import JobOffer

from .agents import MindrisAgents
from .tasks import MindrisTasks

logger = logging.getLogger(__name__)


class MindrisIntelligence:
    """High-level facade over a CrewAI crew for job-offer analysis.

    Usage::

        intelligence = MindrisIntelligence(
            provider="groq",
            model_name="llama3-70b-8192",
        )
        result = intelligence.analyze_job(markdown_text, source_url)
    """

    def __init__(
        self,
        provider: str = "ollama",
        model_name: str = "gemma4:32k",
    ) -> None:
        """Initialise agents and task factories with the specified LLM.

        Args:
            provider: The LLM provider (e.g., "ollama", "groq", "gemini", "openai").
            model_name: The specific model name for the provider.
        """
        self.agents = MindrisAgents(provider=provider, model_name=model_name)
        self.tasks = MindrisTasks()

    def analyze_job(self, job_markdown: str, url: str = "http://unknown") -> CrewOutput:
        """Analyse a job offer and return structured output.

        The URL and description are injected by the pipeline *after* the crew
        finishes, so the LLM only needs to produce the lightweight extraction
        fields (title, company, skills, …).

        Args:
            job_markdown: The job offer body in Markdown format.
            url: Source URL of the offer — stored on the result object by the
                caller, not generated by the LLM.

        Returns:
            A :class:`crewai.CrewOutput` whose ``.pydantic`` attribute holds a
            :class:`database.models.JobOffer` instance when parsing succeeds.
        """
        analyst = self.agents.job_analyst_agent()
        task = self.tasks.analysis_task(analyst, job_markdown, url)

        crew = Crew(
            agents=[analyst],
            tasks=[task],
            process=Process.sequential,
        )

        return crew.kickoff()


async def analyze_job_offer(
    markdown_content: str,
    url: str,
    provider: str = "groq",
    model_name: str = "llama-3.3-70b-versatile",
) -> JobOffer | None:
    """Async wrapper: parse scraped Markdown into a structured JobOffer.

    Runs the synchronous CrewAI crew in a thread executor so it does not
    block the FastAPI event loop.  The raw LLM output is coerced into a
    :class:`~database.models.JobOffer` Pydantic model; the ``url`` and
    ``description_markdown`` fields are injected after parsing.

    Args:
        markdown_content: Clean Markdown of the scraped job-offer page.
        url: Original source URL of the job offer.
        provider: LLM provider to use for extraction.
        model_name: Model identifier for the chosen provider.

    Returns:
        A validated :class:`~database.models.JobOffer` instance, or ``None``
        if parsing fails entirely.
    """
    logger.info("🧠 Analyzing job offer from %s with %s/%s", url, provider, model_name)

    try:
        intelligence = MindrisIntelligence(provider=provider, model_name=model_name)

        # Run synchronous CrewAI in a thread to avoid blocking the event loop
        loop = asyncio.get_running_loop()
        result: CrewOutput = await loop.run_in_executor(
            None, intelligence.analyze_job, markdown_content, url
        )

        # ── Try Pydantic output first (output_json=JobOffer) ─────────────────
        if hasattr(result, "pydantic") and result.pydantic:
            job_offer: JobOffer = result.pydantic
            job_offer.url = url
            job_offer.description_markdown = markdown_content[:2000]
            logger.info(
                "✅ JobOffer extracted: '%s' @ '%s' — %d hard skills",
                job_offer.title,
                job_offer.company,
                len(job_offer.hard_skills),
            )
            return job_offer

        # ── Fallback: parse raw JSON string ──────────────────────────────────
        raw = str(result.raw).strip()
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start != -1 and end > start:
            data = json.loads(raw[start:end])
            data["url"] = url
            data["description_markdown"] = markdown_content[:2000]
            job_offer = JobOffer.model_validate(data)
            logger.info(
                "✅ JobOffer parsed from raw JSON: '%s' @ '%s'",
                job_offer.title,
                job_offer.company,
            )
            return job_offer

        logger.warning("⚠️ Could not extract JobOffer — no valid JSON in LLM output.")
        return None

    except Exception:
        logger.exception("❌ analyze_job_offer() failed for %s", url)
        return None
